version: '3'
services:
  app:
    build: .
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    working_dir: /go/src/GOSecretProject/cmd/
    ports:
      - "9000:9000"
    stdin_open: true
    tty: true
    network_mode: host