version: '3'
services:
  app:
    build: .
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    working_dir: /go/src/haha/cmd/
    ports:
      - "8001:8001"
    stdin_open: true
    tty: true
    network_mode: host