version: '3'
services:
  app:
    build: .
    env_file:
      - ../env.list
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    working_dir: /go/src/GOSecretProject/cmd/
    ports:
      - "9000:9000"
    stdin_open: true
    tty: true
    network_mode: host

  postgres:
    image: postgres
    restart: always
    volumes:
      - ./config/initDB.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ../env.list